version: "3"
services:
  frontend:
    build:
      context: ./frontend-repo
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - data-volume:/app/public/data

  backend:
    build:
      context: ./backend-repo
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - data-volume:/app/public/data

volumes:
  data-volume:
